agent: Agent.class

Agent.class: Agent.java
	JAVA_HOME=/usr/usc/jdk/1.6.0_23 PATH=/usr/usc/jdk/1.6.0_23/bin:${PATH} javac Agent.java

run: Agent.class
	JAVA_HOME=/usr/usc/jdk/1.6.0_23/bin/ PATH=/usr/usc/jdk/1.6.0_23/bin:${PATH} java Agent

